name: build-test-release

on:
  workflow_call:
    inputs:
      variables:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    name: building
    steps:
      - name: Test Variables
        run: |
          echo "the variables for ${{ fromJSON(inputs.variables).Name }} are"  '${{ inputs.variables }}'
          echo "The buildtype for this specific build job is ${{ fromJSON(inputs.variables).BuildType }}"
          echo "The create release for this specific build job is ${{ fromJSON(inputs.variables).create-release }}"
  test:
    needs: [build]
    name: further testing ${{ matrix.os }}
    uses: ./.github/workflows/testing-jobs.yml
    strategy:
      matrix:
        os:
        - windows
        - linux
        - macOS
    with:
      variables: '${{ inputs.variables }}'
      build-config: ${{ tojson(matrix) }}
  release:
    runs-on: ubuntu-latest
    needs: [test]
    name: Releasing
    if: ${{ fromJSON(inputs.variables).create-release == true}}
    steps:
      - name: Test Variables
        run: |
          echo "the variables for ${{ fromJSON(inputs.variables).Name }} are"  '${{ inputs.variables }}'
          echo "The buildtype for this specific build job is ${{ fromJSON(inputs.variables).BuildType }}"
          echo "The create release for this specific build job is ${{ fromJSON(inputs.variables).create-release }}"
