name: build

on:
  workflow_call:
    inputs:
      variables:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test Variables
        run: |
          echo "the variables for ${{ fromJSON(inputs.variables).Name }} are"  '${{ inputs.variables }}'
          echo "The buildtype for this specific build job is ${{ fromJSON(inputs.variables).BuildType }}"
          echo "The create release for this specific build job is ${{ fromJSON(inputs.variables).create-release }}"
