name: build-test-release

on:
  workflow_call:
    inputs:
      variables:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    name: building
    steps:
      - name: Test Variables
        run: |
          echo "the variables for ${{ fromJSON(inputs.variables).Name }} are"  '${{ inputs.variables }}'
          echo "The buildtype for this specific build job is ${{ fromJSON(inputs.variables).BuildType }}"
          echo "The create release for this specific build job is ${{ fromJSON(inputs.variables).create-release }}"
  test:
    needs: [build]
    uses: ./.github/workflows/testing-jobs.yml
    with:
      variables: '${{ inputs.variables }}'
  secondary-build:
    runs-on: ubuntu-latest
    needs: [pars-vars]
    name: building Unrelated to matrix
    steps:
      - name: Test Variables
        run: |
          echo "The builds defined from the previous job are ${{ fromJSON(needs.pars-vars.outputs.variables).Builds }}"
  release:
    runs-on: ubuntu-latest
    needs: [test]
    name: Releasing
    if: ${{ fromJSON(inputs.variables).create-release == true}}
    steps:
      - name: Test Variables
        run: |
          echo "the variables for ${{ fromJSON(inputs.variables).Name }} are"  '${{ inputs.variables }}'
          echo "The buildtype for this specific build job is ${{ fromJSON(inputs.variables).BuildType }}"
          echo "The create release for this specific build job is ${{ fromJSON(inputs.variables).create-release }}"
