name: Build and Test

on: workflow_dispatch


jobs:
  build-and-test:
    strategy:
      matrix:
        os:
        - windows
        - linux
        - macOS
    uses: ./.github/workflows/build-and-test.yml
    with:
      build-config: ${{ tojson(matrix) }}
