name: Main Build Job

on: push

jobs:
  pars-vars:
    runs-on: ubuntu-latest
    outputs:
      variables: ${{ steps.pars-vars.outputs.json }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Variables
        uses: ./.github/actions/parse-vars
        id: pars-vars
        with:
          path: ".github/variables/myvars.env"
          log-variables: true
      - name: Using Variables
        run: |
          echo "The configuration name from the previous step is ${{ steps.pars-vars.outputs.configurationname }}"
          echo "The environment from the previous step is ${{ steps.pars-vars.outputs.environment }}"
          echo "The builds defined from the previous step are ${{ steps.pars-vars.outputs.builds }}"
  build-jobs:
    runs-on: ubuntu-latest
    needs: [pars-vars]
    name: building ${{ matrix.target.name }}
    strategy:
      matrix:
        target: ${{ fromJSON(fromJSON(needs.pars-vars.outputs.variables).Builds) }}
    steps:
      - name: Test Variables
        run: |
          echo "The buildtype for this specific build job is ${{ matrix.target.BuildType }}"
          echo "The create release for this specific build job is ${{ matrix.target.create-release }}"
