name: testing

on:
  workflow_call:
    inputs:
      variables:
        required: true
        type: string
      build-config:
        type: string
jobs:
  testing-further:
    runs-on: ubuntu-latest
    name: testing-further
    steps:
    - run: echo "testing"
